services:
  db:
    container_name: lab2-db-1
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
       - 5431:5432
  etl:
    build: .
    depends_on:
      - db
volumes:
  db_data:


